# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filter_labels_cpp <- function(labels, keep_ids) {
    invisible(.Call(`_pliman_filter_labels_cpp`, labels, keep_ids))
}

analyze_objects_cpp <- function(img_sexp, bin_sexp = NULL, index_str = "NB", r = 1L, g = 2L, b = 3L, re = 4L, nir = 5L, swir = 6L, threshold_method = "Otsu", threshold_val = 0.5, k_adj = 0.1, windowsize = 15L, invert = FALSE, erode_sz = 0L, dilate_sz = 0L, opening_sz = 0L, closing_sz = 0L, filter_sz = 0L, fill_hull = FALSE, filter_order = character(), return_exact = FALSE, watershed = TRUE, tolerance = 1.0, ext = 1L, haralick = FALSE, har_nbins = 32L, har_band = 1L, smooth = 0L) {
    .Call(`_pliman_analyze_objects_cpp`, img_sexp, bin_sexp, index_str, r, g, b, re, nir, swir, threshold_method, threshold_val, k_adj, windowsize, invert, erode_sz, dilate_sz, opening_sz, closing_sz, filter_sz, fill_hull, filter_order, return_exact, watershed, tolerance, ext, haralick, har_nbins, har_band, smooth)
}

bwlabel_cpp <- function(img_sexp) {
    .Call(`_pliman_bwlabel_cpp`, img_sexp)
}

sobel_help <- function(A) {
    .Call(`_pliman_sobel_help`, A)
}

help_edge_thinning <- function(img) {
    .Call(`_pliman_help_edge_thinning`, img)
}

bounding_box <- function(img, edge) {
    .Call(`_pliman_bounding_box`, img, edge)
}

isolate_objects5 <- function(img, labels) {
    .Call(`_pliman_isolate_objects5`, img, labels)
}

help_isolate_object <- function(R_sexp, G_sexp, B_sexp, labels_sexp, remove_bg, edge) {
    .Call(`_pliman_help_isolate_object`, R_sexp, G_sexp, B_sexp, labels_sexp, remove_bg, edge)
}

help_shp <- function(rows, cols, dims, buffer_x, buffer_y) {
    .Call(`_pliman_help_shp`, rows, cols, dims, buffer_x, buffer_y)
}

helper_guo_hall <- function(image) {
    .Call(`_pliman_helper_guo_hall`, image)
}

idw_interpolation_cpp <- function(x, y, values, new_x, new_y, power = 2) {
    .Call(`_pliman_idw_interpolation_cpp`, x, y, values, new_x, new_y, power)
}

help_label <- function(matrix, max_gap = 2L) {
    .Call(`_pliman_help_label`, matrix, max_gap)
}

rcpp_st_perimeter <- function(sf_coords) {
    .Call(`_pliman_rcpp_st_perimeter`, sf_coords)
}

uuid_v7 <- function() {
    .Call(`_pliman_uuid_v7`)
}

helper_entropy <- function(values, precision = 2L) {
    .Call(`_pliman_helper_entropy`, values, precision)
}

corners_to_wkt <- function(cornersList) {
    .Call(`_pliman_corners_to_wkt`, cornersList)
}

correct_image_rcpp <- function(img, K, model) {
    .Call(`_pliman_correct_image_rcpp`, img, K, model)
}

transform_polygons <- function(geometries, shift_x, shift_y, angle_deg, scale_x, scale_y) {
    .Call(`_pliman_transform_polygons`, geometries, shift_x, shift_y, angle_deg, scale_x, scale_y)
}

cpp_as_native_raster <- function(img_sexp, dims) {
    .Call(`_pliman_cpp_as_native_raster`, img_sexp, dims)
}

image_histogram_cpp <- function(img_sexp, nbins = 256L) {
    .Call(`_pliman_image_histogram_cpp`, img_sexp, nbins)
}

cpp_image_transpose <- function(img_sexp) {
    .Call(`_pliman_cpp_image_transpose`, img_sexp)
}

cpp_clahe <- function(img_sexp, nx = 8L, ny = 8L, clip_limit = 3.0, nbins = 256L) {
    .Call(`_pliman_cpp_clahe`, img_sexp, nx, ny, clip_limit, nbins)
}

cpp_make_brush <- function(size, shape = "disc", step = TRUE, sigma = 0.3, angle = 45.0) {
    .Call(`_pliman_cpp_make_brush`, size, shape, step, sigma, angle)
}

float_to_raw_cpp <- function(input) {
    .Call(`_pliman_float_to_raw_cpp`, input)
}

raw_to_float_cpp <- function(input) {
    .Call(`_pliman_raw_to_float_cpp`, input)
}

rgb_to_hsb_help <- function(r, g, b) {
    .Call(`_pliman_rgb_to_hsb_help`, r, g, b)
}

rgb_to_srgb_help <- function(rgb) {
    .Call(`_pliman_rgb_to_srgb_help`, rgb)
}

compute_single_index_cpp <- function(img_sexp, ind, r = 1L, g = 2L, b = 3L, re = 4L, nir = 5L, swir = 6L, storage = "auto") {
    .Call(`_pliman_compute_single_index_cpp`, img_sexp, ind, r, g, b, re, nir, swir, storage)
}

help_area <- function(coord) {
    .Call(`_pliman_help_area`, coord)
}

help_slide <- function(coord, fp = 1L) {
    .Call(`_pliman_help_slide`, coord, fp)
}

help_distpts <- function(data) {
    .Call(`_pliman_help_distpts`, data)
}

help_centdist <- function(data) {
    .Call(`_pliman_help_centdist`, data)
}

help_centdist2 <- function(data) {
    .Call(`_pliman_help_centdist2`, data)
}

help_rotate <- function(polygon, angle) {
    .Call(`_pliman_help_rotate`, polygon, angle)
}

help_align <- function(coord) {
    .Call(`_pliman_help_align`, coord)
}

help_lw <- function(coord) {
    .Call(`_pliman_help_lw`, coord)
}

help_eigen_ratio <- function(coord) {
    .Call(`_pliman_help_eigen_ratio`, coord)
}

help_calliper <- function(coord) {
    .Call(`_pliman_help_calliper`, coord)
}

help_elongation <- function(coord) {
    .Call(`_pliman_help_elongation`, coord)
}

help_flip_y <- function(shape) {
    .Call(`_pliman_help_flip_y`, shape)
}

help_flip_x <- function(shape) {
    .Call(`_pliman_help_flip_x`, shape)
}

help_mc <- function(coords) {
    .Call(`_pliman_help_mc`, coords)
}

help_limits <- function(mat) {
    .Call(`_pliman_help_limits`, mat)
}

help_moments <- function(data) {
    .Call(`_pliman_help_moments`, data)
}

get_area_mask <- function(mask_sexp) {
    .Call(`_pliman_get_area_mask`, mask_sexp)
}

find_card_corners_cpp <- function(contour) {
    .Call(`_pliman_find_card_corners_cpp`, contour)
}

poly_measures_cpp <- function(contours, calc_pcv = FALSE) {
    .Call(`_pliman_poly_measures_cpp`, contours, calc_pcv)
}

compute_chulls_cpp <- function(contours) {
    .Call(`_pliman_compute_chulls_cpp`, contours)
}

poly_measures_minimal_cpp <- function(contours) {
    .Call(`_pliman_poly_measures_minimal_cpp`, contours)
}

poly_measures_disease_cpp <- function(contours) {
    .Call(`_pliman_poly_measures_disease_cpp`, contours)
}

polygon_to_binary <- function(polygon) {
    .Call(`_pliman_polygon_to_binary`, polygon)
}

sum_true_cols <- function(x) {
    .Call(`_pliman_sum_true_cols`, x)
}

help_poly_angles <- function(coords) {
    .Call(`_pliman_help_poly_angles`, coords)
}

help_smoth <- function(coords, niter) {
    .Call(`_pliman_help_smoth`, coords, niter)
}

smoothContours <- function(contours, window_size = 3L) {
    .Call(`_pliman_smoothContours`, contours, window_size)
}

efourier_cpp <- function(coords_list, nharm) {
    .Call(`_pliman_efourier_cpp`, coords_list, nharm)
}

efourier_norm_cpp <- function(efourier_list, start) {
    .Call(`_pliman_efourier_norm_cpp`, efourier_list, start)
}

rfourier_cpp <- function(contours, nharm_vec) {
    .Call(`_pliman_rfourier_cpp`, contours, nharm_vec)
}

tfourier_cpp <- function(contours, nharm_vec) {
    .Call(`_pliman_tfourier_cpp`, contours, nharm_vec)
}

gpa_cpp <- function(contours, tol = 1e-5, max_iter = 100L) {
    .Call(`_pliman_gpa_cpp`, contours, tol, max_iter)
}

object_bbox_cpp <- function(contours) {
    .Call(`_pliman_object_bbox_cpp`, contours)
}

get_point_at_dist <- function(coords, cum_dist, target_dist) {
    .Call(`_pliman_get_point_at_dist`, coords, cum_dist, target_dist)
}

get_closest_idx_forward <- function(rail, tx, ty, start_idx) {
    .Call(`_pliman_get_closest_idx_forward`, rail, tx, ty, start_idx)
}

make_grid_structure <- function(rail1, rail2, nrow, ncol, buffer_col, buffer_row, plot_width_opt, plot_height_opt) {
    .Call(`_pliman_make_grid_structure`, rail1, rail2, nrow, ncol, buffer_col, buffer_row, plot_width_opt, plot_height_opt)
}

make_grid_curved <- function(rail1, rail2, nrow, ncol, curved = TRUE, density = 20L) {
    .Call(`_pliman_make_grid_curved`, rail1, rail2, nrow, ncol, curved, density)
}

make_grid_landmarks <- function(rail1, rail2, anchors1, anchors2, nrow, curved = TRUE, density = 30L) {
    .Call(`_pliman_make_grid_landmarks`, rail1, rail2, anchors1, anchors2, nrow, curved, density)
}

make_grid_structure_old <- function(rail1, rail2, nrow, ncol, buffer_col, buffer_row, plot_width_opt, plot_height_opt) {
    .Call(`_pliman_make_grid_structure_old`, rail1, rail2, nrow, ncol, buffer_col, buffer_row, plot_width_opt, plot_height_opt)
}

make_grid_curved_old <- function(rail1, rail2, nrow, ncol, curved = TRUE, density = 20L) {
    .Call(`_pliman_make_grid_curved_old`, rail1, rail2, nrow, ncol, curved, density)
}

make_grid_landmarks_old <- function(rail1, rail2, anchors1, anchors2, nrow, curved = TRUE, density = 30L) {
    .Call(`_pliman_make_grid_landmarks_old`, rail1, rail2, anchors1, anchors2, nrow, curved, density)
}

cpp_shapefile_measures <- function(geoms) {
    .Call(`_pliman_cpp_shapefile_measures`, geoms)
}

threshold_adaptive <- function(mat, k, windowsize, maxsd) {
    .Call(`_pliman_threshold_adaptive`, mat, k, windowsize, maxsd)
}

help_otsu <- function(img_sexp) {
    .Call(`_pliman_help_otsu`, img_sexp)
}

cpp_binary_threshold <- function(img_sexp, threshold, op = 1L, return_raw = TRUE) {
    .Call(`_pliman_cpp_binary_threshold`, img_sexp, threshold, op, return_raw)
}

color_labels_cpp <- function(labels_sexp) {
    .Call(`_pliman_color_labels_cpp`, labels_sexp)
}

detect_veins_cpp <- function(R_sexp, G_sexp, B_sexp, labels_sexp, sigma1 = 0.75, sigma2 = 3.75, threshold = -1.0, channel = 0L, erode_size = -1L, rel_erode = 0.01, thinning = FALSE, return_map = FALSE) {
    .Call(`_pliman_detect_veins_cpp`, R_sexp, G_sexp, B_sexp, labels_sexp, sigma1, sigma2, threshold, channel, erode_size, rel_erode, thinning, return_map)
}

#' Fast C++ retrieval of available system physical RAM in bytes (Windows, Linux, macOS)
#'
#' @export
get_free_ram_cpp <- function() {
    .Call(`_pliman_get_free_ram_cpp`)
}

#' Fast C++ raster extraction engine without GDAL
#'
#' @param values Matrix of raster values (ncell x nlyr).
#' @param n_row Number of raster rows.
#' @param n_col Number of raster columns.
#' @param n_lyr Number of raster layers.
#' @param bbox_raster Vector c(xmin, xmax, ymin, ymax).
#' @param geoms_r Rcpp::List of polygon geometries for each feature.
#' @param fun CharacterVector of summary functions ("none", "mean", "median", "sum", "min", "max", "sd", "count", "quantile", "quantiles").
#' @param exact Logical, whether to compute exact pixel area fraction coverage.
#' @param return_coverage_area Logical, whether to include coverage_area column in raw pixel output.
#' @param subdiv Number of subdivisions per dimension when exact = TRUE.
#' @param summarize_quantiles NumericVector of quantile probabilities (between 0 and 1) when "quantiles" is requested.
#' @export
cpp_extract_raster <- function(values, n_row, n_col, n_lyr, bbox_raster, geoms_r, fun = as.character( c("none")), exact = FALSE, return_coverage_area = FALSE, subdiv = 10L, summarize_quantiles = as.numeric( c(0.05, 0.975))) {
    .Call(`_pliman_cpp_extract_raster`, values, n_row, n_col, n_lyr, bbox_raster, geoms_r, fun, exact, return_coverage_area, subdiv, summarize_quantiles)
}

gaussian_blur_cpp <- function(img_sexp, sigma) {
    .Call(`_pliman_gaussian_blur_cpp`, img_sexp, sigma)
}

haralick_features_cpp <- function(labels, ref_sexp, nc = 32L) {
    .Call(`_pliman_haralick_features_cpp`, labels, ref_sexp, nc)
}

help_get_rgb <- function(R_sexp, G_sexp, B_sexp, labels_sexp) {
    .Call(`_pliman_help_get_rgb`, R_sexp, G_sexp, B_sexp, labels_sexp)
}

help_get_renir <- function(RE_sexp, NIR_sexp, labels_sexp) {
    .Call(`_pliman_help_get_renir`, RE_sexp, NIR_sexp, labels_sexp)
}

#' Native C++ Sub-Pixel Image Stack Alignment (ECC Maximization)
#'
#' High-performance C++ implementation of Enhanced Correlation Coefficient (ECC)
#' maximization with multi-scale Gaussian pyramids for sub-pixel image alignment.
#'
#' @param images List of `Image` objects or arrays.
#' @param ref_idx 0-indexed reference image index.
#' @param method Character: `"ecc"` (affine) or `"translation"`.
#' @param crop Logical: automatically crop empty affine borders.
#' @param levels Integer: number of pyramid levels (default: 3).
#' @param max_iter Integer: max iterations per level (default: 50).
#' @param eps Numeric: convergence tolerance (default: 1e-4).
#' @param verbose Logical: print progress.
#'
#' @return A named list containing `aligned`, `matrices`, `statuses`, and `crop_box`.
#' @export
align_stack_cpp <- function(images, ref_idx = 0L, method = "ecc", crop = TRUE, levels = 3L, max_iter = 50L, eps = 1e-4, verbose = TRUE) {
    .Call(`_pliman_align_stack_cpp`, images, ref_idx, method, crop, levels, max_iter, eps, verbose)
}

#' Native C++ Extended Depth of Field (EDF) Focus Stacking via Modified Laplacian
#'
#' Ultra-fast analytical multi-focus image fusion using spatial Modified Laplacian (ML)
#' energy maps. Ideal for large image stacks (50-500 images) where deep learning
#' networks are computationally heavy.
#'
#' @param images List of aligned `Image` objects or arrays.
#' @param blend Character: `"soft"` (weighted softmax blending) or `"hard"` (maximum sharpness selection).
#' @param radius Integer: smoothing window radius for local sharpness aggregation (default: 3).
#' @param power Numeric: exponent weight for soft blending (default: 6.0).
#'
#' @return A fused `Image` object.
#' @export
fuse_laplacian_cpp <- function(images, blend = "soft", radius = 3L, power = 6.0) {
    .Call(`_pliman_fuse_laplacian_cpp`, images, blend, radius, power)
}

read_image_cpp <- function(filename) {
    .Call(`_pliman_read_image_cpp`, filename)
}

write_image_cpp <- function(img_sexp, filename, quality = 95L) {
    .Call(`_pliman_write_image_cpp`, img_sexp, filename, quality)
}

preprocess_yolo_file_cpp <- function(filename, target_size = 640L) {
    .Call(`_pliman_preprocess_yolo_file_cpp`, filename, target_size)
}

draw_yolo_detections_bgr_cpp <- function(bm, xmin, ymin, xmax, ymax, labels, scores, colors, lwd = 2L, hud_text = "", font_scale = 1.0, keypoints = NULL, kpt_threshold = 0.3, kpt_radius = 4L, draw_skeleton = TRUE, draw_boxes = TRUE, track_ids = NULL, flash = NULL, history_x = NULL, history_y = NULL, roi = NULL, roi_label = "", count_line = NULL, count_line_label = "", counted = NULL, hide_outside_roi = TRUE, hide_counted = TRUE, flash_counted = TRUE, show_text = TRUE, show_conf = TRUE, show_class = TRUE, show_id = FALSE, badge = TRUE, pad_scale = 1.0, mask_labels = NULL, mask_alpha = 0.4, mask_offset_x = 0L, mask_offset_y = 0L, draw_masks = TRUE, mask_ids = NULL, hud_pos = "top-right", hud_layout = "vertical") {
    .Call(`_pliman_draw_yolo_detections_bgr_cpp`, bm, xmin, ymin, xmax, ymax, labels, scores, colors, lwd, hud_text, font_scale, keypoints, kpt_threshold, kpt_radius, draw_skeleton, draw_boxes, track_ids, flash, history_x, history_y, roi, roi_label, count_line, count_line_label, counted, hide_outside_roi, hide_counted, flash_counted, show_text, show_conf, show_class, show_id, badge, pad_scale, mask_labels, mask_alpha, mask_offset_x, mask_offset_y, draw_masks, mask_ids, hud_pos, hud_layout)
}

crop_bgr_cpp <- function(bm, x1, y1, x2, y2) {
    .Call(`_pliman_crop_bgr_cpp`, bm, x1, y1, x2, y2)
}

save_frame_bgr_cpp <- function(bm, filename, quality = 90L) {
    .Call(`_pliman_save_frame_bgr_cpp`, bm, filename, quality)
}

swap_rgb_bgr_inplace_cpp <- function(bm) {
    .Call(`_pliman_swap_rgb_bgr_inplace_cpp`, bm)
}

load_frame_bgr_cpp <- function(filename) {
    .Call(`_pliman_load_frame_bgr_cpp`, filename)
}

image_hreflect_cpp <- function(img_sexp) {
    .Call(`_pliman_image_hreflect_cpp`, img_sexp)
}

image_vreflect_cpp <- function(img_sexp) {
    .Call(`_pliman_image_vreflect_cpp`, img_sexp)
}

image_resize_cpp <- function(img_sexp, out_w, out_h, filter = 0L) {
    .Call(`_pliman_image_resize_cpp`, img_sexp, out_w, out_h, filter)
}

image_rotate_cpp <- function(img_sexp, angle_deg, bg_color) {
    .Call(`_pliman_image_rotate_cpp`, img_sexp, angle_deg, bg_color)
}

stitch_pair_cpp <- function(img1, img2, direction = "horizontal", blend = TRUE, overlap_hint = 0.2) {
    .Call(`_pliman_stitch_pair_cpp`, img1, img2, direction, blend, overlap_hint)
}

compute_index_means_cpp <- function(idx_mat, labels_sexp, valid_ids) {
    .Call(`_pliman_compute_index_means_cpp`, idx_mat, labels_sexp, valid_ids)
}

rgb_to_hsb_cpp <- function(R_sexp, G_sexp, B_sexp) {
    .Call(`_pliman_rgb_to_hsb_cpp`, R_sexp, G_sexp, B_sexp)
}

detect_line_segments <- function(image_sexp, X, Y, scale = 0.8, sigma_scale = 0.6, quant = 2.0, ang_th = 22.5, log_eps = 0.0, density_th = 0.7, n_bins = 1024L, need_to_union = 0L, union_ang_th = 7, union_use_NFA = 0L, union_log_eps = 0.0, length_threshold = 5, dist_threshold = 5) {
    .Call(`_pliman_detect_line_segments`, image_sexp, X, Y, scale, sigma_scale, quant, ang_th, log_eps, density_th, n_bins, need_to_union, union_ang_th, union_use_NFA, union_log_eps, length_threshold, dist_threshold)
}

median_filter_cpp <- function(img_sexp, nrow, ncol, nch, radius) {
    .Call(`_pliman_median_filter_cpp`, img_sexp, nrow, ncol, nch, radius)
}

median_filter_binary_cpp <- function(img_sexp, nrow, ncol, nch, radius) {
    .Call(`_pliman_median_filter_binary_cpp`, img_sexp, nrow, ncol, nch, radius)
}

#' Fast external erosion
#'
#' @param img A logical matrix representing the binary image.
#' @param raio Radius of the structuring element (integer >= 1).
#' @param forma Shape of the structuring element ("disc" or "square").
erode_external_cpp <- function(img, raio = 3L, forma = "disc") {
    .Call(`_pliman_erode_external_cpp`, img, raio, forma)
}

#' Standard morphological erosion
#'
#' @param img A logical matrix representing the binary image.
#' @param raio Radius of the structuring element (integer >= 1).
#' @param forma Shape of the structuring element ("disc" or "square").
erode_cpp <- function(img, raio = 3L, forma = "disc") {
    .Call(`_pliman_erode_cpp`, img, raio, forma)
}

#' Fast morphological dilation
#'
#' @param img A logical matrix representing the binary image.
#' @param raio Radius of the structuring element (integer >= 1).
#' @param forma Shape of the structuring element ("disc" or "square").
dilate_cpp <- function(img, raio = 3L, forma = "disc") {
    .Call(`_pliman_dilate_cpp`, img, raio, forma)
}

#' Fast internal hole filling (with optional maximum hole size and neck distance check)
#'
#' @param img A logical matrix representing the binary image.
#' @param max_size Maximum area (in pixels) of internal holes to fill. If <= 0 (default), fills all holes.
#' @param min_neck_dist Minimum foreground thickness (distance to background) surrounding a hole to allow filling. Default = 0.0 (fill all internal holes).
fill_holes_cpp <- function(img, max_size = -1.0, min_neck_dist = 0.0) {
    .Call(`_pliman_fill_holes_cpp`, img, max_size, min_neck_dist)
}

#' Fast conservative erosion pipeline
#'
#' @param img A logical matrix representing the binary image.
#' @param raio_erosao Radius for erosion step (integer >= 1).
#' @param raio_dilatacao Radius for dilation step (integer >= 1).
#' @param forma Shape of the structuring element ("disc" or "square").
erosao_conservativa <- function(img, raio_erosao = 3L, raio_dilatacao = 3L, forma = "disc") {
    .Call(`_pliman_erosao_conservativa`, img, raio_erosao, raio_dilatacao, forma)
}

#' Grayscale Reflection Removal via Masked Median Inpainting
#'
#' Removes specular reflections from a grayscale index matrix before thresholding.
#' Algorithm:
#'   1. Auto-detects which class is background by sampling border pixels after Otsu.
#'   2. BFS from image borders marks all background pixels reachable from the exterior.
#'   3. Internal holes = background-class pixels NOT reached by BFS (enclosed by grain).
#'   4. Each internal hole pixel is replaced by the MEDIAN of its foreground (grain)
#'      neighbours within `radius`. This is orientation-agnostic and never touches
#'      the grain boundary or the external background.
#'
#' @param img Grayscale index matrix.
#' @param radius Neighbourhood radius for median sampling (default = 5).
#' @param has_white_bg Unused — background class is detected automatically.
#' @return Corrected grayscale matrix.
#' @export
remove_reflection_cpp <- function(img, radius = 5L, has_white_bg = TRUE) {
    .Call(`_pliman_remove_reflection_cpp`, img, radius, has_white_bg)
}

help_binary_filters_cpp <- function(img_sexp, erode = 0L, dilate = 0L, opening = 0L, closing = 0L, filter = 0L, fill_hull = FALSE, filter_order = as.character( c("erode", "dilate", "opening", "closing", "filter", "fill_hull")), max_size = -1.0, min_neck_dist = 0.0) {
    .Call(`_pliman_help_binary_filters_cpp`, img_sexp, erode, dilate, opening, closing, filter, fill_hull, filter_order, max_size, min_neck_dist)
}

has_native_camera_cpp <- function() {
    .Call(`_pliman_has_native_camera_cpp`)
}

list_native_cameras_cpp <- function() {
    .Call(`_pliman_list_native_cameras_cpp`)
}

list_camera_formats_cpp <- function(cam_id = 0L) {
    .Call(`_pliman_list_camera_formats_cpp`, cam_id)
}

open_native_camera_cpp <- function(cam_id = 0L, target_w = 0L, target_h = 0L) {
    .Call(`_pliman_open_native_camera_cpp`, cam_id, target_w, target_h)
}

get_camera_dims_cpp <- function(cam_ptr) {
    .Call(`_pliman_get_camera_dims_cpp`, cam_ptr)
}

grab_native_frame_cpp <- function(cam_ptr, out_bm, crop_x1 = 0L, crop_y1 = 0L, crop_w = 0L, crop_h = 0L) {
    .Call(`_pliman_grab_native_frame_cpp`, cam_ptr, out_bm, crop_x1, crop_y1, crop_w, crop_h)
}

close_native_camera_cpp <- function(cam_ptr) {
    invisible(.Call(`_pliman_close_native_camera_cpp`, cam_ptr))
}

create_native_window_cpp <- function(title = "pliman - YOLO Detection", width = 640L, height = 480L, fullscreen = FALSE) {
    .Call(`_pliman_create_native_window_cpp`, title, width, height, fullscreen)
}

show_native_frame_cpp <- function(win_ptr, bm, preserve_aspect = TRUE) {
    invisible(.Call(`_pliman_show_native_frame_cpp`, win_ptr, bm, preserve_aspect))
}

poll_native_window_cpp <- function(win_ptr) {
    .Call(`_pliman_poll_native_window_cpp`, win_ptr)
}

close_native_window_cpp <- function(win_ptr) {
    invisible(.Call(`_pliman_close_native_window_cpp`, win_ptr))
}

set_native_window_title_cpp <- function(win_ptr, title) {
    invisible(.Call(`_pliman_set_native_window_title_cpp`, win_ptr, title))
}

has_native_video_cpp <- function() {
    .Call(`_pliman_has_native_video_cpp`)
}

get_native_video_info_cpp <- function(video_path) {
    .Call(`_pliman_get_native_video_info_cpp`, video_path)
}

split_video_native_cpp <- function(video_path, output_dir, prefix = "frame_", digits = 6L, format = "jpg", quality = 95L, target_fps = 0.0, target_n = 0L, verbose = TRUE, callback = NULL) {
    .Call(`_pliman_split_video_native_cpp`, video_path, output_dir, prefix, digits, format, quality, target_fps, target_n, verbose, callback)
}

extract_contours_cpp <- function(labels) {
    .Call(`_pliman_extract_contours_cpp`, labels)
}

pliman_gpu_info_cpp <- function() {
    .Call(`_pliman_pliman_gpu_info_cpp`)
}

clear_onnx_sessions_cpp <- function() {
    invisible(.Call(`_pliman_clear_onnx_sessions_cpp`))
}

run_onnx_inference_cpp <- function(tensor_vec, tensor_dims, model_path, lib_path, num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_onnx_inference_cpp`, tensor_vec, tensor_dims, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_sam2_inference_cpp <- function(tensor_vec, points_x, points_y, point_labels, encoder_path, decoder_path, lib_path, num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_sam2_inference_cpp`, tensor_vec, points_x, points_y, point_labels, encoder_path, decoder_path, lib_path, num_threads, use_gpu, device_id)
}

run_grounding_dino_cpp <- function(pixel_values, input_ids, token_type_ids, attention_mask, model_path, lib_path, box_threshold = 0.25, text_threshold = 0.25, iou_threshold = 0.5, num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_grounding_dino_cpp`, pixel_values, input_ids, token_type_ids, attention_mask, model_path, lib_path, box_threshold, text_threshold, iou_threshold, num_threads, use_gpu, device_id)
}

run_sam2_instances_cpp <- function(tensor_vec, boxes, orig_w, orig_h, encoder_path, decoder_path, lib_path, num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_sam2_instances_cpp`, tensor_vec, boxes, orig_w, orig_h, encoder_path, decoder_path, lib_path, num_threads, use_gpu, device_id)
}

run_sam2_persam_cpp <- function(tensor_vec, exemplar_x, exemplar_y, orig_w, orig_h, encoder_path, decoder_path, lib_path, sim_threshold = 0.5, min_dist = 16.0, iou_threshold = 0.5, max_objects = 200L, feat_res = 256L, num_threads = 0L, use_gpu = FALSE, device_id = -1L, precomputed_prototypes = NULL) {
    .Call(`_pliman_run_sam2_persam_cpp`, tensor_vec, exemplar_x, exemplar_y, orig_w, orig_h, encoder_path, decoder_path, lib_path, sim_threshold, min_dist, iou_threshold, max_objects, feat_res, num_threads, use_gpu, device_id, precomputed_prototypes)
}

inspect_onnx_model_cpp <- function(model_path, lib_path) {
    .Call(`_pliman_inspect_onnx_model_cpp`, model_path, lib_path)
}

run_depth_anything_cpp <- function(tensor_vec, in_w, in_h, orig_w, orig_h, model_path, lib_path, num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_depth_anything_cpp`, tensor_vec, in_w, in_h, orig_w, orig_h, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_dinov2_cpp <- function(tensor_vec, in_w, in_h, patch_size = 14L, return_pca = TRUE, model_path = "", lib_path = "", num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_dinov2_cpp`, tensor_vec, in_w, in_h, patch_size, return_pca, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_yolo_cpp <- function(tensor_vec, orig_w, orig_h, conf_threshold = 0.25, iou_threshold = 0.45, model_path = "", lib_path = "", num_threads = 0L, use_gpu = FALSE, device_id = -1L, need_masks = TRUE, return_features = FALSE, txt_feats = NULL) {
    .Call(`_pliman_run_yolo_cpp`, tensor_vec, orig_w, orig_h, conf_threshold, iou_threshold, model_path, lib_path, num_threads, use_gpu, device_id, need_masks, return_features, txt_feats)
}

run_yolo_cls_cpp <- function(tensor_vec, model_path = "", lib_path = "", num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_yolo_cls_cpp`, tensor_vec, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_clip_vision_cpp <- function(tensor_vec, in_w = 224L, in_h = 224L, model_path = "", lib_path = "", num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_clip_vision_cpp`, tensor_vec, in_w, in_h, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_clip_text_cpp <- function(input_ids, batch_size, seq_len = 77L, attention_mask = NULL, model_path = "", lib_path = "", num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_clip_text_cpp`, input_ids, batch_size, seq_len, attention_mask, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_stardist_cpp <- function(tensor_vec, in_w, in_h, orig_w, orig_h, prob_threshold = 0.5, nms_threshold = 0.3, model_path = "", lib_path = "", num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_stardist_cpp`, tensor_vec, in_w, in_h, orig_w, orig_h, prob_threshold, nms_threshold, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_super_resolution_cpp <- function(tensor_vec, in_w, in_h, scale = 4L, tile_size = 256L, tile_pad = 16L, model_path = "", lib_path = "", num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_super_resolution_cpp`, tensor_vec, in_w, in_h, scale, tile_size, tile_pad, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_dual_image_inference_cpp <- function(img1_vec, img2_vec, in_w, in_h, model_path = "", lib_path = "", num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_dual_image_inference_cpp`, img1_vec, img2_vec, in_w, in_h, model_path, lib_path, num_threads, use_gpu, device_id)
}

preprocess_yolo_cpp <- function(img_data, target_size = 640L) {
    .Call(`_pliman_preprocess_yolo_cpp`, img_data, target_size)
}

canny_edge_detector <- function(image, X, Y, s = 2, low_thr = 3, high_thr = 10, accGrad = FALSE) {
    .Call(`_pliman_canny_edge_detector`, image, X, Y, s, low_thr, high_thr, accGrad)
}

skeleton_mat_cpp <- function(binary_mat, closing_rad = 1L, fill_size = 200L, min_len = 10L, rad_fac = 1.2, dissolve_cycles = TRUE, smooth = TRUE) {
    .Call(`_pliman_skeleton_mat_cpp`, binary_mat, closing_rad, fill_size, min_len, rad_fac, dissolve_cycles, smooth)
}

analyze_root_system_cpp <- function(binary_mat, pixel_size = 1.0, prune_length_px = 12L, cluster_radius_px = 8.0, crown_x_in = -1.0, crown_y_in = -1.0, num_classes = 4L, diameter_bins = NULL, n_depth_slices = 10L, max_order = 3L, gravitropic_alpha = 1.5, closing_rad = 1L, fill_size = 200L, rad_fac = 1.2, dissolve_cycles = TRUE) {
    .Call(`_pliman_analyze_root_system_cpp`, binary_mat, pixel_size, prune_length_px, cluster_radius_px, crown_x_in, crown_y_in, num_classes, diameter_bins, n_depth_slices, max_order, gravitropic_alpha, closing_rad, fill_size, rad_fac, dissolve_cycles)
}

update_tracker_cpp <- function(xmin, ymin, xmax, ymax, labels, scores, state, count_line = NULL, roi = NULL, max_dist = 120.0, min_iou = 0.25, max_lost = 15L, max_history = 30L) {
    .Call(`_pliman_update_tracker_cpp`, xmin, ymin, xmax, ymax, labels, scores, state, count_line, roi, max_dist, min_iou, max_lost, max_history)
}

watershed_cpp <- function(img_r, tolerance = 1.0, ext = 1L) {
    .Call(`_pliman_watershed_cpp`, img_r, tolerance, ext)
}

help_dist_transform <- function(bin) {
    .Call(`_pliman_help_dist_transform`, bin)
}

