# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

analyze_objects3_cpp <- function(img_sexp, bin_sexp = NULL, index_str = "NB", r = 1L, g = 2L, b = 3L, re = 4L, nir = 5L, swir = 6L, threshold_method = "Otsu", threshold_val = 0.5, k_adj = 0.1, windowsize = 15L, invert = FALSE, erode_sz = 0L, dilate_sz = 0L, opening_sz = 0L, closing_sz = 0L, filter_sz = 0L, fill_hull = FALSE, filter_order = character(), return_exact = FALSE, watershed = TRUE, tolerance = 1.0, ext = 1L, haralick = FALSE, har_nbins = 32L, har_band = 1L, smooth = 0L, return_contours = TRUE) {
    .Call(`_pliman_analyze_objects3_cpp`, img_sexp, bin_sexp, index_str, r, g, b, re, nir, swir, threshold_method, threshold_val, k_adj, windowsize, invert, erode_sz, dilate_sz, opening_sz, closing_sz, filter_sz, fill_hull, filter_order, return_exact, watershed, tolerance, ext, haralick, har_nbins, har_band, smooth, return_contours)
}

bwlabel_cpp <- function(img_sexp) {
    .Call(`_pliman_bwlabel_cpp`, img_sexp)
}

filter_labels_cpp <- function(labels, keep_ids) {
    invisible(.Call(`_pliman_filter_labels_cpp`, labels, keep_ids))
}

analyze_objects_cpp <- function(img_sexp, bin_sexp = NULL, index_str = "NB", r = 1L, g = 2L, b = 3L, re = 4L, nir = 5L, swir = 6L, threshold_method = "Otsu", threshold_val = 0.5, k_adj = 0.1, windowsize = 15L, invert = FALSE, erode_sz = 0L, dilate_sz = 0L, opening_sz = 0L, closing_sz = 0L, filter_sz = 0L, fill_hull = FALSE, filter_order = character(), return_exact = FALSE, watershed = TRUE, tolerance = 1.0, ext = 1L, haralick = FALSE, har_nbins = 32L, har_band = 1L, smooth = 0L) {
    .Call(`_pliman_analyze_objects_cpp`, img_sexp, bin_sexp, index_str, r, g, b, re, nir, swir, threshold_method, threshold_val, k_adj, windowsize, invert, erode_sz, dilate_sz, opening_sz, closing_sz, filter_sz, fill_hull, filter_order, return_exact, watershed, tolerance, ext, haralick, har_nbins, har_band, smooth)
}

sobel_help <- function(A) {
    .Call(`_pliman_sobel_help`, A)
}

help_edge_thinning <- function(img) {
    .Call(`_pliman_help_edge_thinning`, img)
}

bounding_box <- function(img, edge) {
    .Call(`_pliman_bounding_box`, img, edge)
}

isolate_objects5 <- function(img, labels) {
    .Call(`_pliman_isolate_objects5`, img, labels)
}

help_isolate_object <- function(R_sexp, G_sexp, B_sexp, labels_sexp, remove_bg, edge) {
    .Call(`_pliman_help_isolate_object`, R_sexp, G_sexp, B_sexp, labels_sexp, remove_bg, edge)
}

help_shp <- function(rows, cols, dims, buffer_x, buffer_y) {
    .Call(`_pliman_help_shp`, rows, cols, dims, buffer_x, buffer_y)
}

helper_guo_hall <- function(image) {
    .Call(`_pliman_helper_guo_hall`, image)
}

idw_interpolation_cpp <- function(x, y, values, new_x, new_y, power = 2) {
    .Call(`_pliman_idw_interpolation_cpp`, x, y, values, new_x, new_y, power)
}

help_label <- function(matrix, max_gap = 2L) {
    .Call(`_pliman_help_label`, matrix, max_gap)
}

rcpp_st_perimeter <- function(sf_coords) {
    .Call(`_pliman_rcpp_st_perimeter`, sf_coords)
}

uuid_v7 <- function() {
    .Call(`_pliman_uuid_v7`)
}

helper_entropy <- function(values, precision = 2L) {
    .Call(`_pliman_helper_entropy`, values, precision)
}

corners_to_wkt <- function(cornersList) {
    .Call(`_pliman_corners_to_wkt`, cornersList)
}

correct_image_rcpp <- function(img, K, model) {
    .Call(`_pliman_correct_image_rcpp`, img, K, model)
}

transform_polygons <- function(geometries, shift_x, shift_y, angle_deg, scale_x, scale_y) {
    .Call(`_pliman_transform_polygons`, geometries, shift_x, shift_y, angle_deg, scale_x, scale_y)
}

cpp_as_native_raster <- function(img_sexp, dims) {
    .Call(`_pliman_cpp_as_native_raster`, img_sexp, dims)
}

image_histogram_cpp <- function(img_sexp, nbins = 256L) {
    .Call(`_pliman_image_histogram_cpp`, img_sexp, nbins)
}

cpp_image_transpose <- function(img_sexp) {
    .Call(`_pliman_cpp_image_transpose`, img_sexp)
}

cpp_clahe <- function(img_sexp, nx = 8L, ny = 8L, clip_limit = 3.0, nbins = 256L) {
    .Call(`_pliman_cpp_clahe`, img_sexp, nx, ny, clip_limit, nbins)
}

cpp_make_brush <- function(size, shape = "disc", step = TRUE, sigma = 0.3, angle = 45.0) {
    .Call(`_pliman_cpp_make_brush`, size, shape, step, sigma, angle)
}

float_to_raw_cpp <- function(input) {
    .Call(`_pliman_float_to_raw_cpp`, input)
}

raw_to_float_cpp <- function(input) {
    .Call(`_pliman_raw_to_float_cpp`, input)
}

rgb_to_hsb_help <- function(r, g, b) {
    .Call(`_pliman_rgb_to_hsb_help`, r, g, b)
}

rgb_to_srgb_help <- function(rgb) {
    .Call(`_pliman_rgb_to_srgb_help`, rgb)
}

compute_single_index_cpp <- function(img_sexp, ind, r = 1L, g = 2L, b = 3L, re = 4L, nir = 5L, swir = 6L, storage = "auto") {
    .Call(`_pliman_compute_single_index_cpp`, img_sexp, ind, r, g, b, re, nir, swir, storage)
}

help_area <- function(coord) {
    .Call(`_pliman_help_area`, coord)
}

help_slide <- function(coord, fp = 1L) {
    .Call(`_pliman_help_slide`, coord, fp)
}

help_distpts <- function(data) {
    .Call(`_pliman_help_distpts`, data)
}

help_centdist <- function(data) {
    .Call(`_pliman_help_centdist`, data)
}

help_centdist2 <- function(data) {
    .Call(`_pliman_help_centdist2`, data)
}

help_rotate <- function(polygon, angle) {
    .Call(`_pliman_help_rotate`, polygon, angle)
}

help_align <- function(coord) {
    .Call(`_pliman_help_align`, coord)
}

help_lw <- function(coord) {
    .Call(`_pliman_help_lw`, coord)
}

help_eigen_ratio <- function(coord) {
    .Call(`_pliman_help_eigen_ratio`, coord)
}

help_calliper <- function(coord) {
    .Call(`_pliman_help_calliper`, coord)
}

help_elongation <- function(coord) {
    .Call(`_pliman_help_elongation`, coord)
}

help_flip_y <- function(shape) {
    .Call(`_pliman_help_flip_y`, shape)
}

help_flip_x <- function(shape) {
    .Call(`_pliman_help_flip_x`, shape)
}

help_mc <- function(coords) {
    .Call(`_pliman_help_mc`, coords)
}

help_limits <- function(mat) {
    .Call(`_pliman_help_limits`, mat)
}

help_moments <- function(data) {
    .Call(`_pliman_help_moments`, data)
}

get_area_mask <- function(mask_sexp) {
    .Call(`_pliman_get_area_mask`, mask_sexp)
}

find_card_corners_cpp <- function(contour) {
    .Call(`_pliman_find_card_corners_cpp`, contour)
}

poly_measures_cpp <- function(contours, calc_pcv = FALSE) {
    .Call(`_pliman_poly_measures_cpp`, contours, calc_pcv)
}

compute_chulls_cpp <- function(contours) {
    .Call(`_pliman_compute_chulls_cpp`, contours)
}

poly_measures_minimal_cpp <- function(contours) {
    .Call(`_pliman_poly_measures_minimal_cpp`, contours)
}

poly_measures_disease_cpp <- function(contours) {
    .Call(`_pliman_poly_measures_disease_cpp`, contours)
}

polygon_to_binary <- function(polygon) {
    .Call(`_pliman_polygon_to_binary`, polygon)
}

sum_true_cols <- function(x) {
    .Call(`_pliman_sum_true_cols`, x)
}

help_poly_angles <- function(coords) {
    .Call(`_pliman_help_poly_angles`, coords)
}

help_smoth <- function(coords, niter) {
    .Call(`_pliman_help_smoth`, coords, niter)
}

smoothContours <- function(contours, window_size = 3L) {
    .Call(`_pliman_smoothContours`, contours, window_size)
}

efourier_cpp <- function(coords_list, nharm) {
    .Call(`_pliman_efourier_cpp`, coords_list, nharm)
}

efourier_norm_cpp <- function(efourier_list, start) {
    .Call(`_pliman_efourier_norm_cpp`, efourier_list, start)
}

rfourier_cpp <- function(contours, nharm_vec) {
    .Call(`_pliman_rfourier_cpp`, contours, nharm_vec)
}

tfourier_cpp <- function(contours, nharm_vec) {
    .Call(`_pliman_tfourier_cpp`, contours, nharm_vec)
}

gpa_cpp <- function(contours, tol = 1e-5, max_iter = 100L) {
    .Call(`_pliman_gpa_cpp`, contours, tol, max_iter)
}

object_bbox_cpp <- function(contours) {
    .Call(`_pliman_object_bbox_cpp`, contours)
}

get_point_at_dist <- function(coords, cum_dist, target_dist) {
    .Call(`_pliman_get_point_at_dist`, coords, cum_dist, target_dist)
}

get_closest_idx_forward <- function(rail, tx, ty, start_idx) {
    .Call(`_pliman_get_closest_idx_forward`, rail, tx, ty, start_idx)
}

make_grid_structure <- function(rail1, rail2, nrow, ncol, buffer_col, buffer_row, plot_width_opt, plot_height_opt) {
    .Call(`_pliman_make_grid_structure`, rail1, rail2, nrow, ncol, buffer_col, buffer_row, plot_width_opt, plot_height_opt)
}

make_grid_curved <- function(rail1, rail2, nrow, ncol, curved = TRUE, density = 20L) {
    .Call(`_pliman_make_grid_curved`, rail1, rail2, nrow, ncol, curved, density)
}

make_grid_landmarks <- function(rail1, rail2, anchors1, anchors2, nrow, curved = TRUE, density = 30L) {
    .Call(`_pliman_make_grid_landmarks`, rail1, rail2, anchors1, anchors2, nrow, curved, density)
}

make_grid_structure_old <- function(rail1, rail2, nrow, ncol, buffer_col, buffer_row, plot_width_opt, plot_height_opt) {
    .Call(`_pliman_make_grid_structure_old`, rail1, rail2, nrow, ncol, buffer_col, buffer_row, plot_width_opt, plot_height_opt)
}

make_grid_curved_old <- function(rail1, rail2, nrow, ncol, curved = TRUE, density = 20L) {
    .Call(`_pliman_make_grid_curved_old`, rail1, rail2, nrow, ncol, curved, density)
}

make_grid_landmarks_old <- function(rail1, rail2, anchors1, anchors2, nrow, curved = TRUE, density = 30L) {
    .Call(`_pliman_make_grid_landmarks_old`, rail1, rail2, anchors1, anchors2, nrow, curved, density)
}

cpp_shapefile_measures <- function(geoms) {
    .Call(`_pliman_cpp_shapefile_measures`, geoms)
}

threshold_adaptive <- function(mat, k, windowsize, maxsd) {
    .Call(`_pliman_threshold_adaptive`, mat, k, windowsize, maxsd)
}

help_otsu <- function(img_sexp) {
    .Call(`_pliman_help_otsu`, img_sexp)
}

cpp_binary_threshold <- function(img_sexp, threshold, op = 1L, return_raw = TRUE) {
    .Call(`_pliman_cpp_binary_threshold`, img_sexp, threshold, op, return_raw)
}

color_labels_cpp <- function(labels_sexp) {
    .Call(`_pliman_color_labels_cpp`, labels_sexp)
}

detect_veins_cpp <- function(R_sexp, G_sexp, B_sexp, labels_sexp, sigma1 = 0.75, sigma2 = 3.75, threshold = -1.0, channel = 0L, erode_size = -1L, rel_erode = 0.01, thinning = FALSE, return_map = FALSE) {
    .Call(`_pliman_detect_veins_cpp`, R_sexp, G_sexp, B_sexp, labels_sexp, sigma1, sigma2, threshold, channel, erode_size, rel_erode, thinning, return_map)
}

#' Fast C++ retrieval of available system physical RAM in bytes (Windows, Linux, macOS)
#'
#' @export
get_free_ram_cpp <- function() {
    .Call(`_pliman_get_free_ram_cpp`)
}

#' Fast C++ raster extraction engine without GDAL
#'
#' @param values Matrix of raster values (ncell x nlyr).
#' @param n_row Number of raster rows.
#' @param n_col Number of raster columns.
#' @param n_lyr Number of raster layers.
#' @param bbox_raster Vector c(xmin, xmax, ymin, ymax).
#' @param geoms_r Rcpp::List of polygon geometries for each feature.
#' @param fun CharacterVector of summary functions ("none", "mean", "median", "sum", "min", "max", "sd", "count", "quantile", "quantiles").
#' @param exact Logical, whether to compute exact pixel area fraction coverage.
#' @param return_coverage_area Logical, whether to include coverage_area column in raw pixel output.
#' @param subdiv Number of subdivisions per dimension when exact = TRUE.
#' @param summarize_quantiles NumericVector of quantile probabilities (between 0 and 1) when "quantiles" is requested.
#' @export
cpp_extract_raster <- function(values, n_row, n_col, n_lyr, bbox_raster, geoms_r, fun = as.character( c("none")), exact = FALSE, return_coverage_area = FALSE, subdiv = 10L, summarize_quantiles = as.numeric( c(0.05, 0.975))) {
    .Call(`_pliman_cpp_extract_raster`, values, n_row, n_col, n_lyr, bbox_raster, geoms_r, fun, exact, return_coverage_area, subdiv, summarize_quantiles)
}

gaussian_blur_cpp <- function(img_sexp, sigma) {
    .Call(`_pliman_gaussian_blur_cpp`, img_sexp, sigma)
}

haralick_features_cpp <- function(labels, ref_sexp, nc = 32L) {
    .Call(`_pliman_haralick_features_cpp`, labels, ref_sexp, nc)
}

help_get_rgb <- function(R_sexp, G_sexp, B_sexp, labels_sexp) {
    .Call(`_pliman_help_get_rgb`, R_sexp, G_sexp, B_sexp, labels_sexp)
}

help_get_renir <- function(RE_sexp, NIR_sexp, labels_sexp) {
    .Call(`_pliman_help_get_renir`, RE_sexp, NIR_sexp, labels_sexp)
}

read_image_cpp <- function(filename) {
    .Call(`_pliman_read_image_cpp`, filename)
}

write_image_cpp <- function(img_sexp, filename, quality = 95L) {
    .Call(`_pliman_write_image_cpp`, img_sexp, filename, quality)
}

image_hreflect_cpp <- function(img_sexp) {
    .Call(`_pliman_image_hreflect_cpp`, img_sexp)
}

image_vreflect_cpp <- function(img_sexp) {
    .Call(`_pliman_image_vreflect_cpp`, img_sexp)
}

image_resize_cpp <- function(img_sexp, out_w, out_h, filter = 0L) {
    .Call(`_pliman_image_resize_cpp`, img_sexp, out_w, out_h, filter)
}

image_rotate_cpp <- function(img_sexp, angle_deg, bg_color) {
    .Call(`_pliman_image_rotate_cpp`, img_sexp, angle_deg, bg_color)
}

compute_index_means_cpp <- function(idx_mat, labels_sexp, valid_ids) {
    .Call(`_pliman_compute_index_means_cpp`, idx_mat, labels_sexp, valid_ids)
}

rgb_to_hsb_cpp <- function(R_sexp, G_sexp, B_sexp) {
    .Call(`_pliman_rgb_to_hsb_cpp`, R_sexp, G_sexp, B_sexp)
}

detect_line_segments <- function(image_sexp, X, Y, scale = 0.8, sigma_scale = 0.6, quant = 2.0, ang_th = 22.5, log_eps = 0.0, density_th = 0.7, n_bins = 1024L, need_to_union = 0L, union_ang_th = 7, union_use_NFA = 0L, union_log_eps = 0.0, length_threshold = 5, dist_threshold = 5) {
    .Call(`_pliman_detect_line_segments`, image_sexp, X, Y, scale, sigma_scale, quant, ang_th, log_eps, density_th, n_bins, need_to_union, union_ang_th, union_use_NFA, union_log_eps, length_threshold, dist_threshold)
}

median_filter_cpp <- function(img_sexp, nrow, ncol, nch, radius) {
    .Call(`_pliman_median_filter_cpp`, img_sexp, nrow, ncol, nch, radius)
}

median_filter_binary_cpp <- function(img_sexp, nrow, ncol, nch, radius) {
    .Call(`_pliman_median_filter_binary_cpp`, img_sexp, nrow, ncol, nch, radius)
}

#' Fast external erosion
#'
#' @param img A logical matrix representing the binary image.
#' @param raio Radius of the structuring element (integer >= 1).
#' @param forma Shape of the structuring element ("disc" or "square").
erode_external_cpp <- function(img, raio = 3L, forma = "disc") {
    .Call(`_pliman_erode_external_cpp`, img, raio, forma)
}

#' Standard morphological erosion
#'
#' @param img A logical matrix representing the binary image.
#' @param raio Radius of the structuring element (integer >= 1).
#' @param forma Shape of the structuring element ("disc" or "square").
erode_cpp <- function(img, raio = 3L, forma = "disc") {
    .Call(`_pliman_erode_cpp`, img, raio, forma)
}

#' Fast morphological dilation
#'
#' @param img A logical matrix representing the binary image.
#' @param raio Radius of the structuring element (integer >= 1).
#' @param forma Shape of the structuring element ("disc" or "square").
dilate_cpp <- function(img, raio = 3L, forma = "disc") {
    .Call(`_pliman_dilate_cpp`, img, raio, forma)
}

#' Fast internal hole filling (with optional maximum hole size and neck distance check)
#'
#' @param img A logical matrix representing the binary image.
#' @param max_size Maximum area (in pixels) of internal holes to fill. If <= 0 (default), fills all holes.
#' @param min_neck_dist Minimum foreground thickness (distance to background) surrounding a hole to allow filling. Default = 0.0 (fill all internal holes).
fill_holes_cpp <- function(img, max_size = -1.0, min_neck_dist = 0.0) {
    .Call(`_pliman_fill_holes_cpp`, img, max_size, min_neck_dist)
}

#' Fast conservative erosion pipeline
#'
#' @param img A logical matrix representing the binary image.
#' @param raio_erosao Radius for erosion step (integer >= 1).
#' @param raio_dilatacao Radius for dilation step (integer >= 1).
#' @param forma Shape of the structuring element ("disc" or "square").
erosao_conservativa <- function(img, raio_erosao = 3L, raio_dilatacao = 3L, forma = "disc") {
    .Call(`_pliman_erosao_conservativa`, img, raio_erosao, raio_dilatacao, forma)
}

#' Grayscale Reflection Removal via Masked Median Inpainting
#'
#' Removes specular reflections from a grayscale index matrix before thresholding.
#' Algorithm:
#'   1. Auto-detects which class is background by sampling border pixels after Otsu.
#'   2. BFS from image borders marks all background pixels reachable from the exterior.
#'   3. Internal holes = background-class pixels NOT reached by BFS (enclosed by grain).
#'   4. Each internal hole pixel is replaced by the MEDIAN of its foreground (grain)
#'      neighbours within `radius`. This is orientation-agnostic and never touches
#'      the grain boundary or the external background.
#'
#' @param img Grayscale index matrix.
#' @param radius Neighbourhood radius for median sampling (default = 5).
#' @param has_white_bg Unused — background class is detected automatically.
#' @return Corrected grayscale matrix.
#' @export
remove_reflection_cpp <- function(img, radius = 5L, has_white_bg = TRUE) {
    .Call(`_pliman_remove_reflection_cpp`, img, radius, has_white_bg)
}

help_binary_filters_cpp <- function(img_sexp, erode = 0L, dilate = 0L, opening = 0L, closing = 0L, filter = 0L, fill_hull = FALSE, filter_order = as.character( c("erode", "dilate", "opening", "closing", "filter", "fill_hull")), max_size = -1.0, min_neck_dist = 0.0) {
    .Call(`_pliman_help_binary_filters_cpp`, img_sexp, erode, dilate, opening, closing, filter, fill_hull, filter_order, max_size, min_neck_dist)
}

extract_contours_cpp <- function(labels) {
    .Call(`_pliman_extract_contours_cpp`, labels)
}

pliman_gpu_info_cpp <- function() {
    .Call(`_pliman_pliman_gpu_info_cpp`)
}

clear_onnx_sessions_cpp <- function() {
    invisible(.Call(`_pliman_clear_onnx_sessions_cpp`))
}

run_onnx_inference_cpp <- function(tensor_vec, tensor_dims, model_path, lib_path, num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_onnx_inference_cpp`, tensor_vec, tensor_dims, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_sam2_inference_cpp <- function(tensor_vec, points_x, points_y, point_labels, encoder_path, decoder_path, lib_path, num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_sam2_inference_cpp`, tensor_vec, points_x, points_y, point_labels, encoder_path, decoder_path, lib_path, num_threads, use_gpu, device_id)
}

run_grounding_dino_cpp <- function(pixel_values, input_ids, token_type_ids, attention_mask, model_path, lib_path, box_threshold = 0.25, text_threshold = 0.25, iou_threshold = 0.5, num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_grounding_dino_cpp`, pixel_values, input_ids, token_type_ids, attention_mask, model_path, lib_path, box_threshold, text_threshold, iou_threshold, num_threads, use_gpu, device_id)
}

run_sam2_instances_cpp <- function(tensor_vec, boxes, orig_w, orig_h, encoder_path, decoder_path, lib_path, num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_sam2_instances_cpp`, tensor_vec, boxes, orig_w, orig_h, encoder_path, decoder_path, lib_path, num_threads, use_gpu, device_id)
}

run_sam2_persam_cpp <- function(tensor_vec, exemplar_x, exemplar_y, orig_w, orig_h, encoder_path, decoder_path, lib_path, sim_threshold = 0.5, min_dist = 16.0, iou_threshold = 0.5, max_objects = 200L, feat_res = 256L, num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_sam2_persam_cpp`, tensor_vec, exemplar_x, exemplar_y, orig_w, orig_h, encoder_path, decoder_path, lib_path, sim_threshold, min_dist, iou_threshold, max_objects, feat_res, num_threads, use_gpu, device_id)
}

inspect_onnx_model_cpp <- function(model_path, lib_path) {
    .Call(`_pliman_inspect_onnx_model_cpp`, model_path, lib_path)
}

run_depth_anything_cpp <- function(tensor_vec, in_w, in_h, orig_w, orig_h, model_path, lib_path, num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_depth_anything_cpp`, tensor_vec, in_w, in_h, orig_w, orig_h, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_dinov2_cpp <- function(tensor_vec, in_w, in_h, patch_size = 14L, return_pca = TRUE, model_path = "", lib_path = "", num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_dinov2_cpp`, tensor_vec, in_w, in_h, patch_size, return_pca, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_yolo_cpp <- function(tensor_vec, orig_w, orig_h, conf_threshold = 0.25, iou_threshold = 0.45, model_path = "", lib_path = "", num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_yolo_cpp`, tensor_vec, orig_w, orig_h, conf_threshold, iou_threshold, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_yolo_cls_cpp <- function(tensor_vec, model_path = "", lib_path = "", num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_yolo_cls_cpp`, tensor_vec, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_stardist_cpp <- function(tensor_vec, in_w, in_h, orig_w, orig_h, prob_threshold = 0.5, nms_threshold = 0.3, model_path = "", lib_path = "", num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_stardist_cpp`, tensor_vec, in_w, in_h, orig_w, orig_h, prob_threshold, nms_threshold, model_path, lib_path, num_threads, use_gpu, device_id)
}

run_super_resolution_cpp <- function(tensor_vec, in_w, in_h, scale = 4L, tile_size = 256L, tile_pad = 16L, model_path = "", lib_path = "", num_threads = 0L, use_gpu = FALSE, device_id = -1L) {
    .Call(`_pliman_run_super_resolution_cpp`, tensor_vec, in_w, in_h, scale, tile_size, tile_pad, model_path, lib_path, num_threads, use_gpu, device_id)
}

canny_edge_detector <- function(image, X, Y, s = 2, low_thr = 3, high_thr = 10, accGrad = FALSE) {
    .Call(`_pliman_canny_edge_detector`, image, X, Y, s, low_thr, high_thr, accGrad)
}

watershed_cpp <- function(img_r, tolerance = 1.0, ext = 1L) {
    .Call(`_pliman_watershed_cpp`, img_r, tolerance, ext)
}

help_dist_transform <- function(bin) {
    .Call(`_pliman_help_dist_transform`, bin)
}

